[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Async-DisOAuth"
version = "1.1.3a1"
description = "Helps with discord oauth2"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "requests"
]

[project.urls]
"Homepage" = "https://github.com/Arcader717/DiscordOAuth2"
"Bug Tracker" = "https://github.com/Arcader717/DiscordOAuth2/issues"
"Repository" = "https://github.com/Arcader717/DiscordOAuth2"
"Documentation" = "https://async-disoauth2.readthedocs.io/en/latest/index.html"
